# RENAME FILE TO 'config.yml'
bot:
  owner_ids:
    - 1342323477054619648
    - 1342324394399240333
  prefix: $
  default_bet: 100
  bonus_multiplier: 5 # bonus = default_bet * multiplier
  bonus_cooldown: 12 # Bonus every x hours
